import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
normal.family = "VictorMono Nerd Font Mono"
size = 15

[keyboard]
bindings = [{ key = "Slash", mods = "Control", chars = "\u001f" }]

[shell]
program = "/run/current-system/sw/bin/zsh"
args = ["--login", "-c", "tmux"]

[colors]
transparent_background_colors = true
